# Generated by Django 5.2.4 on 2025-08-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Price',
        ),
    ]
