# Generated by Django 5.2.4 on 2025-08-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_remove_enrollment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='DueDate',
        ),
    ]
