# Generated by Django 5.2.4 on 2025-08-25 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ending_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='starting_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='trainer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='workout_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
